// Earendel Linux Manual Pages Database (Supports EN and ZH)
export interface ManPage {
  name: string;
  section: number;
  synopsis: string;
  descriptionEn: string;
  descriptionZh: string;
  optionsEn: { opt: string; desc: string }[];
  optionsZh: { opt: string; desc: string }[];
  examplesEn: string[];
  examplesZh: string[];
}

export const manDatabase: Record<string, ManPage> = {
  ls: {
    name: 'ls',
    section: 1,
    synopsis: 'ls [OPTION]... [FILE]...',
    descriptionEn: 'List information about the FILEs (the current directory by default). Sort entries alphabetically.',
    descriptionZh: '列出目标文件或目录的信息（默认列出当前工作目录）。文件项默认按字母顺序排序。',
    optionsEn: [
      { opt: '-a, --all', desc: 'do not ignore entries starting with .' },
      { opt: '-l', desc: 'use a long listing format with permissions and sizes' },
      { opt: '-h, --human-readable', desc: 'with -l, print sizes like 1K 234M 2G' },
    ],
    optionsZh: [
      { opt: '-a, --all', desc: '不隐藏以 . 开头的隐藏节点和目录' },
      { opt: '-l', desc: '使用长格式列出权限位、所有者、尺寸及修改时间' },
      { opt: '-h, --human-readable', desc: '结合 -l 以易读的可读单位 (1K, 234M) 展示尺寸' },
    ],
    examplesEn: ['ls -la', 'ls -lh /etc'],
    examplesZh: ['ls -la', 'ls -lh /etc'],
  },
  grep: {
    name: 'grep',
    section: 1,
    synopsis: 'grep [OPTION]... PATTERNS [FILE]...',
    descriptionEn: 'grep searches for PATTERNS in each FILE. PATTERNS is one or more patterns separated by newline characters.',
    descriptionZh: 'grep 在目标文件文本中逐行搜索给定的匹配模式，并打印匹配到的结果行。',
    optionsEn: [
      { opt: '-i, --ignore-case', desc: 'ignore case distinctions in patterns and input' },
      { opt: '-v, --invert-match', desc: 'select non-matching lines' },
      { opt: '-n, --line-number', desc: 'prefix each line of output with 1-based line number' },
    ],
    optionsZh: [
      { opt: '-i, --ignore-case', desc: '忽略大小写差异进行模糊匹配' },
      { opt: '-v, --invert-match', desc: '反向选择，只打印不符合匹配条件的行' },
      { opt: '-n, --line-number', desc: '在每一行匹配输出前标明该行在原文件中的起始行号' },
    ],
    examplesEn: ['grep -i "ubuntu" /etc/os-release', 'grep -n "root" /etc/passwd'],
    examplesZh: ['grep -i "ubuntu" /etc/os-release', 'grep -n "root" /etc/passwd'],
  },
  vi: {
    name: 'vi',
    section: 1,
    synopsis: 'vi [OPTION] [file...]',
    descriptionEn: 'Vim is a text editor that is upwards compatible to Vi. It can be used to edit all kinds of plain text.',
    descriptionZh: 'Vi/Vim 是一款全屏模态文本编辑器。包含 COMMAND 命令模式与 INSERT 插入编辑模式。',
    optionsEn: [
      { opt: 'i', desc: 'enter INSERT mode before cursor' },
      { opt: ':w', desc: 'write changes to file' },
      { opt: ':wq / :x', desc: 'write changes and quit modal' },
      { opt: ':q!', desc: 'force quit without saving changes' },
    ],
    optionsZh: [
      { opt: 'i', desc: '在光标当前位置前切入 INSERT 插入模式' },
      { opt: ':w', desc: '将修改保存写入文件 (写盘)' },
      { opt: ':wq / :x', desc: '保存文件修改并退出编辑 Modal' },
      { opt: ':q!', desc: '强制放弃修改并退出 Modal' },
    ],
    examplesEn: ['vi welcome.txt', 'vi demo.sh'],
    examplesZh: ['vi welcome.txt', 'vi demo.sh'],
  },
  ufw: {
    name: 'ufw',
    section: 8,
    synopsis: 'ufw [--dry-run] [enable|disable|status|allow|deny] ...',
    descriptionEn: 'ufw is a program for managing a netfilter firewall and aims to provide an easy-to-use interface for the user.',
    descriptionZh: 'ufw 是 Linux 管理 Netfilter 防火墙的简化控制程序，提供直观的端口开放与拒绝屏蔽。',
    optionsEn: [
      { opt: 'status', desc: 'show firewall status and active rule lists' },
      { opt: 'allow PORT', desc: 'allow incoming traffic on specified port' },
      { opt: 'deny PORT', desc: 'deny incoming traffic on specified port (blocks curl/ping)' },
    ],
    optionsZh: [
      { opt: 'status', desc: '查看防火墙启用状态及活跃规则清单' },
      { opt: 'allow PORT', desc: '开放并允许目标端口的网络包连通' },
      { opt: 'deny PORT', desc: '屏蔽拒绝目标端口（物理阻断 curl / ping 访问）' },
    ],
    examplesEn: ['sudo ufw status', 'sudo ufw deny 80'],
    examplesZh: ['sudo ufw status', 'sudo ufw deny 80'],
  },
  apt: {
    name: 'apt',
    section: 8,
    synopsis: 'apt [OPTION]... [COMMAND] [PACKAGE]...',
    descriptionEn: 'apt provides a high-level commandline interface for the package management system in Debian/Ubuntu.',
    descriptionZh: 'apt 为 Debian/Ubuntu 操作系统提供高层级的软件包检索、刷新、安装与卸载管理命令行。',
    optionsEn: [
      { opt: 'update', desc: 'update list of available packages' },
      { opt: 'install PKG', desc: 'install specified package (requires root)' },
      { opt: 'remove PKG', desc: 'remove specified installed package' },
    ],
    optionsZh: [
      { opt: 'update', desc: '刷新更新可用的软件仓库元数据源' },
      { opt: 'install PKG', desc: '安装指定的软件包（需要 sudo / root 提权）' },
      { opt: 'remove PKG', desc: '卸载指定已安装的软件包' },
    ],
    examplesEn: ['sudo apt update', 'sudo apt install neofetch'],
    examplesZh: ['sudo apt update', 'sudo apt install neofetch'],
  },
  docker: {
    name: 'docker',
    section: 1,
    synopsis: 'docker [OPTIONS] COMMAND [ARG...]',
    descriptionEn: 'Docker is a set of platform as a service products that use OS-level virtualization to deliver software in packages called containers.',
    descriptionZh: 'Docker 是一套利用操作系统层级虚拟化技术（容器）来交付软件隔离运行的打包与部署工具。',
    optionsEn: [
      { opt: 'ps [-a]', desc: 'list running or all containers' },
      { opt: 'images', desc: 'list locally available docker images' },
      { opt: 'run -it IMAGE', desc: 'create and run a new container interactively' },
      { opt: 'stop NAME', desc: 'stop a running container instance' },
    ],
    optionsZh: [
      { opt: 'ps [-a]', desc: '列出正在运行的容器（使用 -a 查看包括停止的全部容器）' },
      { opt: 'images', desc: '列出本地容器镜像仓库中的镜像列表' },
      { opt: 'run -it IMAGE', desc: '以交互终端形式创建并启动运行一个新容器' },
      { opt: 'stop NAME', desc: '停止一个指定的容器实例' },
    ],
    examplesEn: ['docker ps', 'docker images', 'docker run -it ubuntu bash'],
    examplesZh: ['docker ps', 'docker images', 'docker run -it ubuntu bash'],
  },
  sl: {
    name: 'sl',
    section: 1,
    synopsis: 'sl [-alF]',
    descriptionEn: 'sl is a joke command to cure your bad habit of mistyping ls as sl.',
    descriptionZh: 'sl 是 Linux 经典的极客黑客解压彩蛋，用来矫正打错 ls 的小习惯。',
    optionsEn: [{ opt: '-a', desc: 'An accident occurred' }],
    optionsZh: [{ opt: '-a', desc: '小火车发生意外情况' }],
    examplesEn: ['sl'],
    examplesZh: ['sl'],
  },
  figlet: {
    name: 'figlet',
    section: 1,
    synopsis: 'figlet [text...]',
    descriptionEn: 'FIGlet prints its input using large characters made up of ordinary screen characters.',
    descriptionZh: 'FIGlet 会将输入的字符串转化为大字号的 3D ASCII 标语文字进行全屏艺术渲染。',
    optionsEn: [{ opt: 'text', desc: 'The input string to render' }],
    optionsZh: [{ opt: 'text', desc: '需要转化的艺术标语文本' }],
    examplesEn: ['figlet Hello', 'figlet Linux'],
    examplesZh: ['figlet Hello', 'figlet Linux'],
  },
  tcpdump: {
    name: 'tcpdump',
    section: 8,
    synopsis: 'tcpdump [-i interface] [expression]',
    descriptionEn: 'tcpdump prints out a description of the contents of packets on a network interface that match the boolean expression.',
    descriptionZh: 'tcpdump 是一款功能强大的命令行网络数据包分析诊断工具，用于捕获和分析网络接口通信流量。',
    optionsEn: [{ opt: '-i IFACE', desc: 'Listen on interface' }],
    optionsZh: [{ opt: '-i IFACE', desc: '指定需要监听抓包的网络接口设备 (如 eth0)' }],
    examplesEn: ['sudo tcpdump -i eth0', 'sudo tcpdump port 80'],
    examplesZh: ['sudo tcpdump -i eth0', 'sudo tcpdump port 80'],
  },
  traceroute: {
    name: 'traceroute',
    section: 8,
    synopsis: 'traceroute [options] host',
    descriptionEn: 'traceroute tracks the route packets taken from an IP network on their way to a given host.',
    descriptionZh: 'traceroute 用来诊断路由路径，显示 IP 网络封包到达目标主机所经过的路由器跳数与延迟。',
    optionsEn: [{ opt: 'host', desc: 'The target destination domain or IP' }],
    optionsZh: [{ opt: 'host', desc: '目标目的主机域名或 IP 地址' }],
    examplesEn: ['traceroute earendel.local', 'traceroute 8.8.8.8'],
    examplesZh: ['traceroute earendel.local', 'traceroute 8.8.8.8'],
  },
  python3: {
    name: 'python3',
    section: 1,
    synopsis: 'python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...',
    descriptionEn: 'Python is an interpreted, interactive, object-oriented programming language.',
    descriptionZh: 'Python 是一种广受欢迎的高级交互式解释型编程语言，广泛用于自动化脚本与算法开发。',
    optionsEn: [{ opt: 'file.py', desc: 'Read and execute code from given script file' }],
    optionsZh: [{ opt: 'file.py', desc: '从指定的脚本文件中读取并解析执行 Python 代码' }],
    examplesEn: ['python3 demo.py', './demo.py'],
    examplesZh: ['python3 demo.py', './demo.py'],
  },
  node: {
    name: 'node',
    section: 1,
    synopsis: 'node [options] [script.js] [arguments]',
    descriptionEn: 'Node.js is a JavaScript runtime built on Chrome\'s V8 JavaScript engine.',
    descriptionZh: 'Node.js 是基于 Chrome V8 运行引擎构建的跨平台 JavaScript 运行时，物理原生支持全套 ES6+ 语法。',
    optionsEn: [{ opt: 'script.js', desc: 'Execute JavaScript source file using V8 engine' }],
    optionsZh: [{ opt: 'script.js', desc: '利用底层原生 V8 引擎解析并执行指定的 JavaScript 源代码文件' }],
    examplesEn: ['node demo.js', './demo.js'],
    examplesZh: ['node demo.js', './demo.js'],
  },
  theme: {
    name: 'theme',
    section: 1,
    synopsis: 'theme [default|matrix|dracula|cyberpunk|monokai]',
    descriptionEn: 'Customize and switch the terminal color scheme dynamically.',
    descriptionZh: '实时动态切换终端的高调配色方案（如骇客绿、吸血鬼紫、赛博朋克等）。',
    optionsEn: [{ opt: 'name', desc: 'Theme preset name (default, matrix, dracula, cyberpunk, monokai)' }],
    optionsZh: [{ opt: 'name', desc: '主题预设名称 (default, matrix, dracula, cyberpunk, monokai)' }],
    examplesEn: ['theme matrix', 'theme dracula', 'theme default'],
    examplesZh: ['theme matrix', 'theme dracula', 'theme default'],
  },
  tar: {
    name: 'tar',
    section: 1,
    synopsis: 'tar [-czvf|-xzvf] archive.tar.gz [file...]',
    descriptionEn: 'tar is an archiving utility designed to store and extract files from an archive file.',
    descriptionZh: 'tar 是 Linux 下经典的高级打包与归档解包工具，用于把多个文件节点合为一个归档文件或进行提取解包。',
    optionsEn: [
      { opt: '-czvf', desc: 'Create a new tar archive with verbose list' },
      { opt: '-xzvf', desc: 'Extract files from a tar archive with verbose list' },
    ],
    optionsZh: [
      { opt: '-czvf', desc: '创建打包一个新的 tar 归档压缩包并印出解包过程' },
      { opt: '-xzvf', desc: '解包提取目标 tar 归档压缩包中的全部节点' },
    ],
    examplesEn: ['tar -czvf backup.tar.gz welcome.txt demo.py', 'tar -xzvf backup.tar.gz'],
    examplesZh: ['tar -czvf backup.tar.gz welcome.txt demo.py', 'tar -xzvf backup.tar.gz'],
  },
  zip: {
    name: 'zip',
    section: 1,
    synopsis: 'zip archive.zip [file...]',
    descriptionEn: 'zip is a compression and file packaging utility for Unix/Linux.',
    descriptionZh: 'zip 是一款广泛使用的打包压缩工具，将一个或多个文件节点压缩为一个 PKZIP 标准包。',
    optionsEn: [{ opt: 'archive.zip', desc: 'Target zip archive name' }],
    optionsZh: [{ opt: 'archive.zip', desc: '生成的 ZIP 压缩文件名称' }],
    examplesEn: ['zip backup.zip welcome.txt demo.sh demo.py'],
    examplesZh: ['zip backup.zip welcome.txt demo.sh demo.py'],
  },
  unzip: {
    name: 'unzip',
    section: 1,
    synopsis: 'unzip archive.zip',
    descriptionEn: 'unzip will list, test, or extract files from a ZIP archive.',
    descriptionZh: 'unzip 用于解压并还原从 zip 压缩文件包中提取出来的全部文件节点。',
    optionsEn: [{ opt: 'archive.zip', desc: 'The zip file to extract' }],
    optionsZh: [{ opt: 'archive.zip', desc: '解压还原的目标 zip 压缩包' }],
    examplesEn: ['unzip backup.zip'],
    examplesZh: ['unzip backup.zip'],
  },
  alias: {
    name: 'alias',
    section: 1,
    synopsis: 'alias [name[=value] ...]',
    descriptionEn: 'Define or display aliases for shell commands.',
    descriptionZh: '定义或列出当前 Shell 环境变量中命令别名的对应映射清单。',
    optionsEn: [{ opt: 'name=value', desc: 'Set alias name to target command value' }],
    optionsZh: [{ opt: 'name=value', desc: '将别名 name 绑定映射为目标指令字符串' }],
    examplesEn: ['alias', 'alias ll=\'ls -la\'', 'alias cls=\'clear\''],
    examplesZh: ['alias', 'alias ll=\'ls -la\'', 'alias cls=\'clear\''],
  },
  whoami: {
    name: 'whoami',
    section: 1,
    synopsis: 'whoami',
    descriptionEn: 'Print the user name associated with the current effective user ID.',
    descriptionZh: '打印当前系统 TTY 终端会话中所处于的有效用户名（如 hello 或 root）。',
    optionsEn: [],
    optionsZh: [],
    examplesEn: ['whoami'],
    examplesZh: ['whoami'],
  },
  who: {
    name: 'who',
    section: 1,
    synopsis: 'who [OPTION]... [ FILE | ARG1 ARG2 ]',
    descriptionEn: 'Print information about users who are currently logged in.',
    descriptionZh: '列出当前系统已登录用户的列表、关联的虚拟终端及登录时间。',
    optionsEn: [],
    optionsZh: [],
    examplesEn: ['who'],
    examplesZh: ['who'],
  },
  which: {
    name: 'which',
    section: 1,
    synopsis: 'which filename ...',
    descriptionEn: 'which returns the pathnames of the files (or links) which would be executed in the current environment.',
    descriptionZh: 'which 在环境变量 PATH 中定位查找可执行命令文件的绝对路径。',
    optionsEn: [{ opt: 'filename', desc: 'Command name to locate' }],
    optionsZh: [{ opt: 'filename', desc: '需要定位的目标命令名称' }],
    examplesEn: ['which python3', 'which node', 'which ls'],
    examplesZh: ['which python3', 'which node', 'which ls'],
  },
  whereis: {
    name: 'whereis',
    section: 1,
    synopsis: 'whereis [options] name...',
    descriptionEn: 'whereis locates the binary, source, and manual page files for specified command names.',
    descriptionZh: 'whereis 定位并展示目标命令的可执行二进制、源码以及 manual 帮助手册文件的存储路径。',
    optionsEn: [{ opt: 'name', desc: 'Command name' }],
    optionsZh: [{ opt: 'name', desc: '目标命令名称' }],
    examplesEn: ['whereis python3', 'whereis ufw'],
    examplesZh: ['whereis python3', 'whereis ufw'],
  },
  find: {
    name: 'find',
    section: 1,
    synopsis: 'find [-H] [-L] [-P] [path...] [expression]',
    descriptionEn: 'find searches the directory tree rooted at each given file name.',
    descriptionZh: 'find 递归搜索遍历给定的目录层级树，寻找符合匹配条件的文件和文件夹节点。',
    optionsEn: [{ opt: '-name pattern', desc: 'Base of file name matches shell pattern' }],
    optionsZh: [{ opt: '-name pattern', desc: '按照文件名模式（支持 * 通配符）进行模糊检索' }],
    examplesEn: ['find . -name "*.py"', 'find /etc -name "hosts"'],
    examplesZh: ['find . -name "*.py"', 'find /etc -name "hosts"'],
  },
  locate: {
    name: 'locate',
    section: 1,
    synopsis: 'locate [OPTION]... PATTERN...',
    descriptionEn: 'locate reads one or more databases prepared by updatedb(8) and writes file names matching at least one of the PATTERNs.',
    descriptionZh: 'locate 从全盘文件系统节点索引库中极速检索符合关键词路径的文件。',
    optionsEn: [{ opt: 'pattern', desc: 'Search pattern keyword' }],
    optionsZh: [{ opt: 'pattern', desc: '路径关键词' }],
    examplesEn: ['locate demo', 'locate bashrc'],
    examplesZh: ['locate demo', 'locate bashrc'],
  },
  tell: {
    name: 'tell',
    section: 1,
    synopsis: 'tell <name>',
    descriptionEn: 'Express romantic feelings with colorful ASCII fireworks and love banner.',
    descriptionZh: '全天下最浪漫的黑客命令行表白彩蛋，用霓虹彩色烟花与心形 Banner 向心上人传递爱意。',
    optionsEn: [{ opt: 'name', desc: 'Name of the person you love' }],
    optionsZh: [{ opt: 'name', desc: '心上人的名字' }],
    examplesEn: ['tell Lucy', 'tell Alice'],
    examplesZh: ['tell Lucy', 'tell Alice'],
  },
  chmod: {
    name: 'chmod',
    section: 1,
    synopsis: 'chmod [OPTION]... MODE[,MODE]... FILE...',
    descriptionEn: 'chmod changes the file mode bits of each given file according to mode.',
    descriptionZh: 'chmod 用来修改文件或目录节点的访问控制权限（支持八进制数字格式 755/644 及 -R 递归传递）。',
    optionsEn: [
      { opt: 'MODE', desc: 'Octal number (e.g. 755, 644) or symbolic mode (+x)' },
      { opt: '-R', desc: 'change files and directories recursively' },
    ],
    optionsZh: [
      { opt: 'MODE', desc: '八进制数字权限 (如 755, 644) 或符号模式 (+x)' },
      { opt: '-R', desc: '递归对目标文件夹及内部所有子节点施加修改' },
    ],
    examplesEn: ['chmod 755 script.sh', 'chmod +x demo.py', 'chmod -R 644 /tmp'],
    examplesZh: ['chmod 755 script.sh', 'chmod +x demo.py', 'chmod -R 644 /tmp'],
  },
  chown: {
    name: 'chown',
    section: 1,
    synopsis: 'chown [OPTION]... [OWNER][:[GROUP]] FILE...',
    descriptionEn: 'chown changes the user and/or group ownership of each given file.',
    descriptionZh: 'chown 修改文件或目录节点的用户所有者 (OWNER) 及属组 (GROUP)。',
    optionsEn: [{ opt: '-R', desc: 'operate on files and directories recursively' }],
    optionsZh: [{ opt: '-R', desc: '递归对目标文件夹及其子项施加修改' }],
    examplesEn: ['chown root:root /etc/shadow', 'chown -R hello:hello /home/hello'],
    examplesZh: ['chown root:root /etc/shadow', 'chown -R hello:hello /home/hello'],
  },
  umask: {
    name: 'umask',
    section: 1,
    synopsis: 'umask [-p] [-S] [mode]',
    descriptionEn: 'The user file-creation mask is set to mode.',
    descriptionZh: '查看或设置当前 Shell 环境下文件和目录创建时的默认权限掩码。',
    optionsEn: [],
    optionsZh: [],
    examplesEn: ['umask'],
    examplesZh: ['umask'],
  },
  tmux: {
    name: 'tmux',
    section: 1,
    synopsis: 'tmux [split|split-h|exit]',
    descriptionEn: 'tmux is a terminal multiplexer that enables a number of terminals to be created, accessed, and controlled from a single screen.',
    descriptionZh: 'tmux 是一款顶级黑客终端复用器，允许在一个网页窗口里拆分上下/左右双独立的极客分屏。',
    optionsEn: [
      { opt: 'split / split-v', desc: 'Split terminal vertically (top and bottom)' },
      { opt: 'split-h', desc: 'Split terminal horizontally (left and right)' },
      { opt: 'exit', desc: 'Close tmux split view' },
    ],
    optionsZh: [
      { opt: 'split / split-v', desc: '开启上下方向分屏窗口' },
      { opt: 'split-h', desc: '开启左右方向分屏窗口' },
      { opt: 'exit', desc: '退出关闭分屏恢复单屏' },
    ],
    examplesEn: ['tmux', 'tmux split-h', 'tmux exit'],
    examplesZh: ['tmux', 'tmux split-h', 'tmux exit'],
  },
  snapshot: {
    name: 'snapshot',
    section: 1,
    synopsis: 'snapshot [save|restore|list|rm] <name>',
    descriptionEn: 'Full system VFS snapshot save and time-machine rollback restore engine.',
    descriptionZh: '全盘虚拟文件系统状态快照保存与时光倒流全物理回滚恢复引擎。',
    optionsEn: [
      { opt: 'save <name>', desc: 'Create a named system VFS snapshot' },
      { opt: 'restore <name>', desc: 'Rollback current VFS tree back to snapshot' },
      { opt: 'list', desc: 'List all saved snapshot checkpoints' },
      { opt: 'rm <name>', desc: 'Delete a snapshot checkpoint' },
    ],
    optionsZh: [
      { opt: 'save <name>', desc: '物理抓取并保存全盘具名文件系统快照' },
      { opt: 'restore <name>', desc: '一键触发时光倒流，全物理回滚还原至快照时刻' },
      { opt: 'list', desc: '罗列全部已存快照历史' },
      { opt: 'rm <name>', desc: '清理移除指定的系统快照' },
    ],
    examplesEn: ['snapshot save init', 'snapshot list', 'snapshot restore init'],
    examplesZh: ['snapshot save init', 'snapshot list', 'snapshot restore init'],
  },
  vfs: {
    name: 'vfs',
    section: 1,
    synopsis: 'vfs [push|pull|remote] [args]',
    descriptionEn: 'Unified VFS Image Push/Pull & Remote Cloud Sync Toolchain.',
    descriptionZh: '统一大一统的 VFS 操作系统镜像 Push/Pull 与云端 / 校内 Hub 级联同步工具链。',
    optionsEn: [
      { opt: 'push', desc: 'Push and export VFS snapshot (Local disk image or Cloud Hub)' },
      { opt: 'pull', desc: 'Pull and unpack VFS snapshot (Local disk image or Cloud Hub)' },
      { opt: 'remote set-url <url|local>', desc: 'Configure Cloud VFS Hub URL (or "local" for offline local disk mode)' },
      { opt: 'remote set-credential [password]', desc: 'Set password & generate non-colliding Machine UUID in /etc/vfs_config' },
    ],
    optionsZh: [
      { opt: 'push', desc: '推流导出全盘镜像（离线模式打到本地，云模式同步远程）' },
      { opt: 'pull', desc: '拉取重塑全盘镜像（离线模式从本地灌盘，云模式同步远程）' },
      { opt: 'remote set-url <url|local>', desc: '配置远程云端 API Endpoint 地址（或设为 local 开启离线模式）' },
      { opt: 'remote set-credential [password]', desc: '在 /etc/vfs_config 配置密码并生成全网唯一的 Machine UUID Identifier' },
    ],
    examplesEn: ['vfs push', 'vfs pull', 'vfs remote set-url local', 'vfs remote set-credential 123456'],
    examplesZh: ['vfs push', 'vfs pull', 'vfs remote set-url local', 'vfs remote set-credential 123456'],
  },
  dpkg: {
    name: 'dpkg',
    section: 1,
    synopsis: 'dpkg -l [package-name-pattern...]',
    descriptionEn: 'dpkg is a tool to install, build, remove and manage Debian packages.',
    descriptionZh: 'dpkg 是 Debian/Ubuntu 系统核心底层包管理器，用于列出和管理全盘已安装的 Base 软件包与第三方生态包。',
    optionsEn: [{ opt: '-l, --list', desc: 'List installed packages concisely' }],
    optionsZh: [{ opt: '-l, --list', desc: '简要罗列全盘底层已安装的软件包列表' }],
    examplesEn: ['dpkg -l'],
    examplesZh: ['dpkg -l'],
  },
  'wasm-calc': {
    name: 'wasm-calc',
    section: 1,
    synopsis: 'wasm-calc [expression]',
    descriptionEn: 'C-compiled Native WebAssembly High-Performance Calculator.',
    descriptionZh: '由 C 语言原生编译的 WebAssembly 极速计算器与高并发数学指令引擎。',
    optionsEn: [],
    optionsZh: [],
    examplesEn: ['wasm-calc 100 * 200'],
    examplesZh: ['wasm-calc 100 * 200'],
  },
  'wasm-sha256': {
    name: 'wasm-sha256',
    section: 1,
    synopsis: 'wasm-sha256 [text]',
    descriptionEn: 'Rust-compiled Native WebAssembly SHA-256 Crypto Engine.',
    descriptionZh: '由 Rust 语言原生编译的 WebAssembly 高性能 SHA-256 哈希计算与密码学引擎。',
    optionsEn: [],
    optionsZh: [],
    examplesEn: ['wasm-sha256 "Hello Earendel"'],
    examplesZh: ['wasm-sha256 "Hello Earendel"'],
  },
  time: {
    name: 'time',
    section: 1,
    synopsis: 'time [command [arguments...]]',
    descriptionEn: 'time runs the specified program command with the given arguments and reports real, user, and sys execution time.',
    descriptionZh: 'time 用于精确测算并统计指定的子指令运行耗时（包括真实时间 real、用户态 CPU 时间 user 与系统内核态时间 sys）。',
    optionsEn: [],
    optionsZh: [],
    examplesEn: ['time wasm-calc 100 * 200', 'time python3 demo.py'],
    examplesZh: ['time wasm-calc 100 * 200', 'time python3 demo.py'],
  },
  ssh: {
    name: 'ssh',
    section: 1,
    synopsis: 'ssh [user@]hostname',
    descriptionEn: 'OpenSSH SSH client for Earendel P2P Mesh & Remote Connection.',
    descriptionZh: 'Earendel 专属 P2P 去中心化网络 WebRTC 远程 Terminal 交互与连接客户端。',
    optionsEn: [
      { opt: '--sdp-offer', desc: 'Generate zero-server WebRTC SDP Offer string' },
      { opt: '--sdp-answer <SDP>', desc: 'Accept SDP Offer and generate SDP Answer' },
    ],
    optionsZh: [
      { opt: '--sdp-offer', desc: '生成无服务器点对点 WebRTC 握手 SDP Offer 字符串' },
      { opt: '--sdp-answer <SDP>', desc: '接收远程 SDP Offer 并生成对等 SDP Answer 响应' },
    ],
    examplesEn: ['ssh hello@usr_a1b2c3d4', 'ssh --sdp-offer'],
    examplesZh: ['ssh hello@usr_a1b2c3d4', 'ssh --sdp-offer'],
  },
  'ssh-keygen': {
    name: 'ssh-keygen',
    section: 1,
    synopsis: 'ssh-keygen [-C comment]',
    descriptionEn: 'Generates, manages and converts authentication keys for SSH.',
    descriptionZh: '使用 Web Crypto API 原生生成与管理标准的 RSA 2048 位 SSH 密钥对（~/.ssh/id_rsa 与 ~/.ssh/id_rsa.pub）。',
    optionsEn: [{ opt: '-C comment', desc: 'Provide a new comment' }],
    optionsZh: [{ opt: '-C comment', desc: '指定密钥文件标注注释' }],
    examplesEn: ['ssh-keygen', 'ssh-keygen -C "hello@earendel"'],
    examplesZh: ['ssh-keygen', 'ssh-keygen -C "hello@earendel"'],
  },
  mesh: {
    name: 'mesh',
    section: 1,
    synopsis: 'mesh [share|join|status|stop] [peer-id]',
    descriptionEn: 'Earendel P2P Mesh Collaboration Suite for instant sandbox sharing and joining.',
    descriptionZh: 'Earendel 专属 P2P 去中心化网格结对协同套件，提供瞬间沙盒开启分享（mesh share）与免代理加入（mesh join）。',
    optionsEn: [
      { opt: 'share', desc: 'Host a new P2P sandbox session and get Peer ID' },
      { opt: 'join <peer-id>', desc: 'Join classmate\'s Earendel sandbox session' },
      { opt: 'status', desc: 'View active mesh session status' },
      { opt: 'stop', desc: 'Stop hosting and unshare active mesh session' },
    ],
    optionsZh: [
      { opt: 'share', desc: '开启一个新的点对点沙盒联机分享会话并取得 Peer ID' },
      { opt: 'join <peer-id>', desc: '通过 Peer ID 连入同伴的 Earendel 点对点沙盒' },
      { opt: 'status', desc: '查看当前的 P2P 联机网格状态' },
      { opt: 'stop', desc: '停止分享并关闭当前 P2P 联机房间' },
    ],
    examplesEn: ['mesh share', 'mesh join peer-earendel-7a9x-2026', 'mesh status', 'mesh stop'],
    examplesZh: ['mesh share', 'mesh join peer-earendel-7a9x-2026', 'mesh status', 'mesh stop'],
  },
  mount: {
    name: 'mount',
    section: 8,
    synopsis: 'mount [-t host] [target_path]',
    descriptionEn: 'Mount a file system or local PC directory using FileSystem Access API.',
    descriptionZh: '挂载文件系统或通过 FileSystem Access API 将宿主机 PC 本地任意物理文件夹直接挂载至 VFS（如 /mnt/host）。',
    optionsEn: [{ opt: '-t host', desc: 'Mount a real local PC directory via browser folder picker' }],
    optionsZh: [{ opt: '-t host', desc: '调起浏览器原生的文件夹选择弹窗，选择并挂载 PC 本地硬盘目录' }],
    examplesEn: ['mount', 'mount -t host /mnt/host'],
    examplesZh: ['mount', 'mount -t host /mnt/host'],
  },
  umount: {
    name: 'umount',
    section: 8,
    synopsis: 'umount target_path',
    descriptionEn: 'Unmount file systems mounted in Earendel VFS.',
    descriptionZh: '卸载选定的已挂载文件系统或宿主机文件夹挂载点。',
    optionsEn: [],
    optionsZh: [],
    examplesEn: ['umount /mnt/host'],
    examplesZh: ['umount /mnt/host'],
  },
  xclip: {
    name: 'xclip',
    section: 1,
    synopsis: 'xclip [-selection clipboard] [-o]',
    descriptionEn: 'Command line interface to browser and host system clipboard.',
    descriptionZh: '命令行工具，用于将终端内容写往宿主机剪贴板，或读取宿主机剪贴板。',
    optionsEn: [{ opt: '-o', desc: 'Output selection from host clipboard' }],
    optionsZh: [{ opt: '-o', desc: '从宿主机剪贴板读取并输出文字' }],
    examplesEn: ['cat file.txt | xclip', 'xclip -o'],
    examplesZh: ['cat file.txt | xclip', 'xclip -o'],
  },
};
